# -*- coding: utf-8 -*-
"""João Pedro Artero - 232_LP_Funcao_ss_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XOddLhoKabt0OJat5FV-wY3ztUjQKyRP

### 1.0 (Função sem retorno sem parâmetro) Faça um programa contendo uma função/método que leia um número e o multiplique por 2. Apresente o resultado. EXEMPLO.
"""

nome = "Guido Van Rossum"
nome2 = "Giovana"
idade = 68
grana = 10541.7862
grana2 = 1200.7862
print(f'{nome} tem {idade} anos e R$ {grana:.2f}')
print("%-20s tem %i anos e R$ %15.2f" %(nome2,idade,grana2))
print("%-20s tem %i anos e R$ %15.2f" %(nome,idade,grana))
print("{0:>30}.".format(nome))

nome = input("Cadastre seu nome: ")
sobrenome = input("Cadastre seu sobrenome: ")
relatorio_nome_completo = nome + " " + sobrenome
print(relatorio_nome_completo)
print(relatorio_nome_completo)
print(relatorio_nome_completo * 50)

#RESPOSTA DA 2
#FAÇA UMA FUNÇÃO/ METODO QUE LEIA DOIS VALORES POSITIVOS E APRESENTE A SOMA
#DOS N NUMEROS EXISTENTES ENTRE ELES
a = int(input("Digite um número para a: "))
b = int(input("Digite um número para b: "))
soma_valores = 0
# 8 > 2
if a > b:
    auxiliar = a
    a = b
    b = auxiliar
#Esta troca é para somar do menor para o maior
for a in range(a,b + 1):
    soma_valores = soma_valores + a
print("A soma é ",soma_valores)

#RESPOSTA DA 3
n = int(input("Insira o valor de n: "))
for i in range (1,n + 1):
    for j in range(1,i + 1):
        r = i * j
        print(r, end = "\t")
    print()

def multiplicar(): # definição da função
    numero = int(input("Insira um número "))
    resultado = numero * 2
    print(resultado) #Função sem retorno nao necessita de return

multiplicar() #Chamada da função

def multiplicar(): # definição da função
    numero = int(input("Insira um número: "))
    resultado = numero * 2
    print("O resultado é: ",resultado)

def somar():
    numero1 = int(input("Insira o primeiro número: "))
    numero2 = int(input("Insira o segundo número: "))
    resultadosoma = numero1 + numero2
    print("O resultado da soma é: ",resultadosoma)
def main(): # É uma boa prática implementar a função main
    print("Calculadora")
    print("+ Somar")
    print("* Multiplicação")
    operacao = input("Qual cálculo você deseja? ")
    if operacao == "*":
        multiplicar()
    elif operacao == "+":
        somar()
    else:
        print("Você não escolheu uma operação\n")
        main()
main()

"""### 1.1 (Função sem retorno sem parâmetro) Faça um programa contendo uma função/método que apresente o valor 1 se o número digitado for positivo e 0 se for negativo."""

def analise():
    numero = int(input("Insira um número: "))
    if numero <= 0:
        print("0, o número é negativo")
    else:
        print("1, o número é positivo")
analise()

"""### 2. (Função sem retorno sem parâmetro) Faça uma função/método que leia dois valores positivos e apresente a soma dos N números existentes entre eles (inclusive).
    Exemplo:
        a = 2
        b = 8
        2 + 3 + 4 + 5 + 6 + 7 + 8
        soma = 35
"""

def operacao():
    a = int(input("Insira um número: "))
    b = int(input("Insira outro número: "))
    soma = 0
    for a in range (a,b + 1):
        soma = soma + a
    print(soma)
operacao()

"""### 3. (Função sem retorno sem parâmetro) Faça uma função/método que receba três números inteiros *a*, *b*, *c* que sejam divisíveis por ***a***. Os valores *b* e *c* representam o intervalo da estrutura de repetição. Apresente a quantidade e os números divisíveis. Não pode usar vetor e função pronta da linguagem Python.
    Exemplo:
        a = 5
        b = 1
        c = 10
        1 % a
        2 % a
        3 % a
        4 % a
        5 % a este valor é divisível
        6 % a
        7
        8
        9
        10 % a este valor é divisível
        qtde = 2

"""

#neste exercício nós colocamos no valor a o numero que sera divisivel;
#no valor b e c será colocado o intervalo da repetição, ou seja : do valor b até o valor c, estamos analisando quantos numeros são divisiveis pelo valor a

def operacao():
    #valor da divisão
    a = int(input("Insira o primeiro valor: "))
    #inicio da estrutura de repetição
    b = int(input("Insira o segundo valor: "))
    #final da estrutura de repetição
    c = int(input("Insira o terceiro valor: "))
    #contador para contabilizar quantos numeros são divisiveis por A
    divisivel = 0
    #estrutura de repetição para identificar os numeros entre os intervalos b e c
    for i in range(b,c + 1):
        #o numero(i) dividido pelo valor a for igual a 0, siginifica que ele é divisivel
        if i % a == 0:
            #aqui é onde adicionamos o numero ao contador de divisao caso o resto dele divido por A seja 0
            divisivel += 1
            #e onde mostra se o numero é divisivel por a
            print(i," é divisível por ",a)
        else:
            print(i," não é divisível por ",a)
    # aqui é onde mostra a quantidade de numeros divisiveis por a
    print("qtde = ",divisivel)

#é interessante utilizar a def main para economizar tempo de processamento do código
def main():
    operacao()
main()

"""### 4. (Função sem retorno sem parâmetro) Faça uma função/método que leia um único valor representado em segundos, converta-o e apresente o resultado em horas, minutos e segundos.
    h = segundos / 3600
    r = resto(segundos / 3600)
    m = r / 60
    s = resto(r / 60)
    Observação 1: resto de uma divisão em Python %.
    Observação 2: a hora, o minuto e o segundo devem ser apresentados como números inteiros.
"""

def hora():
    segundo = int(input("Insira os segundos: ")) # Converter para hora
    hora = segundo / 3600
    resto = segundo % 3600
    minuto = resto / 60
    segundos = resto % 60
    print(f"São {hora:.0f} horas, {minuto:.0f} minutos e {segundos:.0f} segundos.")

def main():
    hora()
main()

"""### 5. (Função sem retorno sem parâmetro) Faça uma função/método que receba o preço antigo e atual de um produto, determine o percentual de acréscimo entre esses valores e apresente-o.
    r = (100 * preco_novo - 100 * preco_antigo) / preco_antigo
"""

def valores():
    valor_antigo = float(input("Insira o valor antigo: "))
    valor_novo = float(input("Insira o novo valor: "))
    resultado = (100 * valor_novo - 100 * valor_antigo) / valor_antigo
    print(f"O acréscimo foi de {resultado:.0f}%.")

def main():
    valores()
main()

"""### 6. (Função sem retorno sem parâmetro) Faça uma função/método que leia um valor inteiro entre 1 e 9 e mostre a seguinte tabela de **multiplicação**
Neste exemplo foi escolhido o número 9.

    1    
    2     4
    3     6     9
    4     8    12    16
    5    10    15    20    25
    6    12    18    24    30    36
    7    14    21    28    35    42    49
    8    16    24    32    40    48    56    64   
    9    18    27    36    45    54    63    72    81
    for i = 1 até n
       for j = 1 até i
       
    Observação: configure o print para não pular linha, use o parâmetro end.
"""

def tabela():
    usuario = int(input("Insira um valor entre 1 e 9: "))
    for i in range(1,usuario + 1):
        for j in range(1,i + 1):
            multiplicacao = i * j
            print(multiplicacao, end = "\t")
        print()

def main():
    tabela()
main()
# Para ter a mesma forma de apresentação use assim o print(r, end = '\t')

"""### 7. (Função sem retorno sem parâmetro) Faça uma função/método que leia três notas de um aluno e uma letra, se a letra for igual a *A*, deverá calcular a média aritimética das notas dos alunos, se for *P*, deverá calcular a média ponderada, com pesos 5, 3 e 2. A média deve ser mostrada ao final.
N1, N2 e N3 são notas.

P1, P2 e P3 são pesos.

Média ponderada = (N1 * P1 + N2 * P2 + N3 * P3 ) / (P1 + P2 + P3)
"""

def nota():
    nota1 = float(input("Insira a primeira nota: "))
    nota2 = float(input("Insira a segunda nota: "))
    nota3 = float(input("Insira a terceira nota: "))
    print("Escolha entre Média aritimetica (A) e Média ponderada (P)")
    menu = input()
    if menu == "a" or menu == "A" :
        media_aritimetica = (nota1 + nota2 + nota3) / 3
        print("Sua média aritimetica é de: ",media_aritimetica)
    elif menu == "p" or menu == "P" :
        mediaponderada = (nota1 * 5 + nota2 * 3 + nota3 * 2) / (5 + 3 + 2)
        print("Sua média ponderada é de: ",mediaponderada)
    else:
        print("Escolha entre Média aritimetica (A) e Média ponderada (P)")
        nota()

def main():
    nota()

main()

"""### 8. (Função sem retorno sem parâmetro) Faça uma função/método que leia uma hora de início e de término de um jogo, ambas divididas em dois valores distintos: hora e minuto. Deverá ser apresentado a duração expressa em minutos, considerando que o tempo máximo de duração de um jogo é de 24 horas e que ele pode começar em um dia e terminar no outro.
    se m_f < m_i
        m_f = m_f + 60
        h_f = h_f - 1
    se h_f < h_i
        h_f = h_f + 24
    tot_m = m_f - m_i
    tot_h = h_f - h_i
    total = tot_h * 60 + tot_m
"""

def hora():
    h_i = int(input("Insira a hora inicial do jogo: "))
    m_i = int(input("Insira o minuto inicial do jogo: "))
    h_f = int(input("Insira a hora final do jogo: "))
    m_f = int(input("Insira o minuto final do jogo: "))

    if m_f < m_i:
        m_f = m_f + 60
        h_f = h_f - 1
    if h_f < h_i:
        h_f = h_f + 24

    tot_m = m_f - m_i
    tot_h = h_f - h_i
    total = tot_h * 60 + tot_m
    if total <= 1440:
        print(total)
    else:
        print("A partida excedeu o tempo limite.")

def main():
    hora()

main()

"""### 9. (Função sem retorno sem parâmetro) Faça uma função/método que leia cinco valores inteiros, determine e mostre o maior e o menor deles. Não pode usar vetor e função pronta da linguagem Python."""

def operacao():
    numero = int(input("Insira um valor: "))
    menor = numero
    maior = numero
    for i in range(4):
        numero = int(input("Insira um valor: "))
        if numero >= maior:
            maior = numero
        else:
            menor = numero
    print("O menor numero é: ",menor," e o maior numero é: ",maior)

def main():
    operacao()
main()

"""### 10. (Função sem retorno sem parâmetro) Faça uma função/método que leia um valor inteiro e positivo N e mostre o valor de S, obtido pelo seguinte cálculo:
###S = 1  +  1/1!  +  1/2!  +  1/3!  + ... +  1/N!

Observvação: Não pode usar vetor e função pronta da linguagem Python.
"""

# Digite seu código aqui.
# S = 1
# S = 1 + 1 + 1/2! + 1/3 + 1/4!
# S = 1 + 1 + 0.5 + 0.16 + 0.041
# S = 2.66 + 0.041
# 3! = 3 * 2 * 1 = 6
# 4! = 1 * 2 * 3 * 4 = 24    1/4!   1/24  = 0.041

# N = int(input('Informe o valor de N termos: '))


def calculo():
    valor = int(input("Insira um valor: "))
    s = 1
    fatorial = 1
    for i in range(1,valor + 1):
        fatorial *= i
        termo = 1 / fatorial
        s + termo
    print(f"O valor de S para N é igual a {valor} é {s}")

def main():
    calculo()
main()