# -*- coding: utf-8 -*-
"""João Pedro Artero - 221_Vetor_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12s5-VVSyLdecNj6Xk2nlHVXEJvVuC-Oh

#**EXERCÍCIOS SOBRE VETOR**

### 1. Faça um programa que calcule e apresente a média de idades de uma sala de 35 alunos.​​
"""

contador = 0
idade = []
acu_idade = 0
for contador in range(3):
    idade.append(int(input("Insira a sua idade...")))
    acu_idade = acu_idade + idade[contador]
    contador = contador + 1
media = acu_idade / contador
print(idade)
print(media)

"""### 2. Faça um programa que calcule e apresente a média de alturas de uma sala de 35 alunos. Informe também quantos alunos **e** quais (índice/posição) são os que possuem idade superior a 25 anos.​ Use dois vetores, um para altura e outro para idade. Não use nenhuma função pronta da linguagem Python.

"""

soma_alturas = 0
altura = [] #declaração de vetores
idade = []
cont = 0
for contador in range(3): #cadastramento
  altura.append(float(input('Informe a altura: ')))
  idade.append(int(input('Informe a idade: ')))
  soma_alturas = soma_alturas + altura[contador]
  cont = cont + 1
media = soma_alturas / cont
print(f'\n\nA média de altura é {media:.2f} metros\n\n')
for contador in range(3): #repetição para pesquisar
  if idade[contador] > 25:
    cont = cont + 1
    print('O aluno', contador+1, f'possui', idade[contador], 'anos & ', altura[contador] )

"""### 3. Faça um programa que carregue um vetor de dez elementos que contenha o nome de pessoas e outro que contenha o peso, encontre qual a pessoa mais gorda e mais magra e apresente o nome o peso das mesmas.​ Use dois vetores, um para peso e outro para nome. Não use nenhuma função pronta da linguagem Python."""

nomes = []
peso = []
for i in range(3):
  nomes.append(input('Digite o seu nome: '))
  peso.append(float(input('Digite o quanto você pesa: ')))

  if i == 0:
    peso_maior = peso[i]
    peso_menor = peso[i]
    nome_maior = nomes[i]
    nome_menor = nomes[i]

  if peso[i] >= peso_maior:
    peso_maior = peso[i]
    nome_maior = nomes[i]

  if peso[i] <= peso_menor:
    peso_menor = peso[i]
    nome_menor = nomes[i]
print(f'A pessoa mais pesada tem {peso_maior} e se chama {nome_maior}')
print(f'A pessoa mais magra tem {peso_menor} e se chama {nome_menor}')

"""### 4. Faça um programa que carregue um vetor com a média de dez alunos, calcule e mostre a MÉDIA DA SALA e quantos alunos estão acima e abaixo da média da sala."""

notas = []
soma_notas = 0
aprovado = 0
reprovado = 0

for i in range(10):
  notas.append(float(input('Insira a sua média ')))
  soma_notas = soma_notas + notas[i]

  if notas[i] >= 6:
    aprovado = aprovado + 1
  else:
    reprovado = reprovado + 1

mediasala = soma_notas / 10
print(f'A média da sala foi de {mediasala}')

print(f'A sala obteve {aprovado} aprovados e {reprovado} reprovados - media equivalente a igual ou maior que 6.')
print(f'A media da sala foi {mediasala}')

"""### 5. Faça um programa que carregue um vetor de oito elementos numéricos inteiros, calcule e mostre os números pares e suas respectivas índices/posições. Não use nenhuma função pronta da linguagem Python.

"""

numeros = []

for i in range(8):
  numeros.append(int(input('Digite um numero inteiro: ')))
  if numeros[i] > 0:
    r = numeros[i] % 2
    if r == 0:
      print('Esse numero é par')
    else:
      print('Esse numero é impar')

"""### 6. Faça um programa que carregue um vetor com dez nomes e faça uma verificação se um determinado nome esta nesse vetor. Não use nenhuma função pronta da linguagem Python.

"""

onome = []
cont = 0

for i in range(4):
  nome.append(input('Digite o nome: '))
nome_pesquisar = input('Qual nome deseja pesquisar? ')
for i in range(len(nome)):
  if nome[i] == nome_pesquisar:
    print(' Nome encontrado')
  else:
    cont = cont + 1
if cont == len(nome):
  print('Nome nao encontrado')

"""### 7. Faça um algoritmo que calcule e apresente a média de alturas superior a 1,80 de 10 alunos. Informe também quantos e quais (índice/posição) são os alunos. Não use nenhuma função pronta da linguagem Python.

"""

altura = []
cont = 0
media = 0
for i in range(2):
  height = float(input('CADASTRE A SUA ALTURA: '))
  altura.append(height)
  if altura[i] > 1.80:
    cont = cont + 1
    media = media + altura[i]
  print('O aluno em', i+1,'posição possui', altura[i], 'de altura')

media_total = media / cont
print()
print(altura[i])
print('Há', cont,'Alunos acima de 1.80')
print('A média de altura de pessoas com mais de 1.80 é', media_total)

"""### 8. Criar um algoritmo que a partir de um vetor de 10 elementos inteiros, crie outros dois vetores que receberão os elementos positivos e negativos e ao final apresente-os. Não use nenhuma função pronta da linguagem Python.

"""

inteiros = []
positivos = []
negativos = []
for i in range(3):
  inteiros.append(int(input('Digite um numero: ')))

for i in range(3):
  if inteiros[i] > 0:
    positivos.append(inteiros[i])
  if inteiros[i] < 0:
    negativos.append(inteiros[i])
print('Os numeros positivos sao:', positivos)
print('Os numeros negativos sao:', negativos)
print('Os numeros inteiros ao total sao:', inteiros)

"""### 9. Criar um algoritmo que leia dados para um vetor de 100 elementos inteiros, imprimir o maior, o menor, o percentual de números pares e a média dos elementos do vetor. Obs.: percentual = quantidade contada * 100 / quantidade total. Não use nenhuma função pronta da linguagem Python.

"""

todos = []
par = []
impar = []
for i in range(3):
  todos.append(int(input('Digite um numero: ')))

for i in range(3):
  if todos[i] > 0:
    r = todos[i] % 2
    if r == 0:
      par.append(todos[i])
    else:
      impar.append(todos[i])
print('Os numeros pares sao:', par)
print('Os numeros impares sao:', impar)
print('Os numeros ao total sao:', todos)

"""### 10. Faça um programa que:

* preencha um vetor com seis elementos numéricos inteiros.

**Calcule e mostre:**

* todos os números pares;
* a quantidade de números pares;
* todos os números ímpares;
* a quantidade de números ímpares
"""

inteiros = []
paresx = []
imparesx = []
pares = 0
impares = 0


for x in range(6):
  inteiros.append(int(input('Digite um numero inteiro: ')))

for x in range(6):
  if inteiros[x] > 0:
    r = inteiros[x] % 2
    if r == 0:
      paresx.append(inteiros[x])
      pares = pares + 1
    if r == 1:
      imparesx.append(inteiros[x])
      impares = impares + 1
print('Inteiros', inteiros)
print('Pares', paresx)
print('Impares', imparesx)
print('Pares', pares)
print('Impares', impares)

"""### 11. Faça um programa que:

* preencha um vetor com sete números inteiros

**Calcule e mostre:**

* os números múltiplos de 2;
* os números múltiplos de 3;
* os números múltiplos de 2 e de 3.
"""



corsa = []
astra2 = []
vectra3 = []
montana = []

for x in range(7):
  corsa.append(int(input('Digite um numero para o Corsinha ficar feliz: ')))

  if corsa[x] %2 == 0:
    astra2.append(corsa[x])

  if corsa[x] %3 == 0:
    vectra3.append(corsa[x])

  if corsa[x] %2 == 0 and corsa[x] %3 == 0:
    montana.append(corsa[x])

print(vectra3)
print(astra2)
print(montana)

"""### 12. Faça um programa que:

* preencha um vetor com quinze elementos inteiros
* verifique a existência de elementos iguais a 30, mostrando os índices/posições em que apareceram.
"""

# Digite seu código aqui.

"""### 13. Faça um programa que:

* preencha um vetor com dez números reais

**Calcule e mostre:**

* a quantidade de números negativos
* a soma dos números positivos desse *vetor*
* não use nenhuma função pronta da linguagem Python
"""

camaro = []
ss = []
ssx = 0
zl1 = []
zl1x = 0
fifty = 0

for x in range(10):
  camaro.append(int(input('Digite um numero inteiro: ')))
  if camaro[x] > 0:
    ss.append(camaro[x])
    ssx = ssx + 1
    fifty = fifty + camaro[x]
  if camaro[x] < 0:
    zl1.append(camaro[x])
    zl1x = zl1x + 1

print('A soma total dos numeros positivos é', fifty)
print('Numeros negativos', zl1x)

"""### 14. Faça um programa que:

* receba dez números inteiros e armazene-os em um vetor
* classifique os números em dois vetores, um com números pares e o outra com os ímpares
* não use nenhuma função pronta da linguagem Python
"""

numeros = []
pares = []
impares = []

for i in range(10):
  numeros.append(int(input('Digite um numero inteiro: ')))
  if numeros[i] > 0:
    r = numeros[i] % 2
    if r == 0:
      pares.append(numeros[i])
      print('Esse numero é par')
    else:
      impares.append(numeros[i])
      print('Esse numero é impar')
print('Estes numeros neste vetor são pares', pares,'e estes aqui sao impares', impares)

"""### 15. Faça um programa que:

* preencha um vetor com quinze números

**Determine e mostre:**

* o maior número e a posição por ele ocupada no vetor
* o menor número e a posição por ele ocupada no vetor
* Não use nenhuma função pronta da linguagem Python
"""

corvette = []
maior = 0
menor = 0
position = 0

for x in range(3):
  corvette.append(int(input('Digite um numero inteiro: ')))
  if corvette[x] > maior:
    maior = corvette[x]
    position += 1
  if corvette[x] < menor:
    menor = corvette[x]
    position += 1
print(f'O maior numero está na posição {position} e o numero é {maior}')
print(f'O menor numero está na posição {position} e o numero é {menor}')

"""#**EXERCÍCIOS - EXTRA**

### 16. Faça um programa que:

* preencha dois vetores com de dez numeros cada
* preencha um terceiro vetor com os números dos dois vetores anteriores ordenados em ordem crescente
"""

# Digite seu código aqui.

"""### 17. Faça um programa que:

* carregue dois vetores com 10 números cada
* faça a multiplicação dos números na mesma posição
* o resultado deverá ser adicionada em um terceiro vetor
* não use nenhuma função pronta da linguagem Python
"""

# Digite seu código aqui.
a = [ 8, 6, 3, 5]
b = [ 3, 2, 8, 1]
c = [8*3, 6*2,]

"""### 18. Faça um programa que:

* leia um vetor de 10 números inteiros
* exiba na tela os números positivos e seus respectivos índices.
* não use nenhuma função pronta da linguagem Python
"""

# Digite seu código aqui.

"""### 19. Faça um programa que:

* insira dez números inteiros em um vetor
* crie um segundo vetor, substituindo os números multiplos de 3 por "999""
* exiba os dois vetores
* não use nenhuma função pronta da linguagem Python
"""

# Digite seu código aqui.

"""### 21. Faça um programa que:

* leia dois vetores (A e B) com cinco posições para números inteiros.
* o programa deve, então, subtrair o primeiro elemento de A do último de B, armazenando o resultado num terceiro vetor, subtrair o segundo elemento de A do penúltimo de B, armazenando o resultado num terceiro vetor e assim por diante.
* ao final, mostre o resultado do terceiro vetor
* não use nenhuma função pronta da linguagem Python
"""

# Digite seu código aqui.

"""###22. Faça um programa que:

* preencha um vetor de cinco números e mostre a saída a seguir:
* imprima a seguinte saída: n1 + n2 + n3 + n4 + n5 = soma_dos_numeros, exemplo 8 + 2 + 1 + 3 + 0 = 14
* não use nenhuma função pronta da linguagem Python

"""

# Digite seu código aqui.

"""### 23. Faça um programa que:
* leia um vetor com quinze posições para números inteiros.
* depois da leitura, divida todos os seus elementos pelo maior valor do vetor.
* Mostre o vetor após os cálculos.
* não use nenhuma função pronta da linguagem Python
"""

# Digite seu código aqui.

"""### 24. Um vetor é palíndromo se ele não se alterar quando o mesmo for invertido. Escreva um programa que verifique se um vetor é palíndromo, fazendo comparação de índice/posição por índice/posição do vetor original (vo) com o vetor invertido (vi). Não use nenhuma função pronta da linguagem Python. A tamanho do vetor pode ser da sua escolha.
Exemplo:
vetor original    vo = {1, 3, 5, 2, 2, 5, 3, 1}  
vetor invertido é vi = {1, 3, 5, 2, 2, 5, 3, 1}
O vetor invertido **é palíndromo**, pois ele invertido é igual ao original

vetor original    vo = {9, 7, 5, 2, 4, 5, 3, 6}  
vetor invertido é vi = {6, 3, 5, 4, 2, 5, 7, 9}
O vetor invertido **não é palíndromo**, pois ele invertido é igual ao original


"""

# Digite seu código aqui.