# -*- coding: utf-8 -*-
"""João Pedro Artero - 221_Matriz_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FT4Wg5tBFGoqRRxtSNHWAvh3qqCoNKFI

### 1. Faça um programa que leia uma matriz 2x3 (2 linhas, 3 colunas). Apresente os elementos da matriz e seus respectivos índices.
"""

matriz = [] # ................................................... Lendo a matriz
for lin in range(2):
    linha = []
    for col in range(3):
        linha.append(int(input('Digite o valor ['+ str(lin) + '][' + str(col) + ']: ')))
        #soma = soma + linha[col]
    matriz.append(linha)
#print da soma dos salários
for lin in range(2):  # ...................................Apresentando a matriz
    for col in range(3):
	    print(matriz[lin][col], end='\t')
    print()

"""### 2. Faça um programa que carregue uma matriz 2 x 2, que representa o salário de 4 funcionários, calcule e mostre a soma total de todos os elementos que será o montante pago pela empresa a esses funcionários."""

salario = []
soma_total = 0
for lin in range(2):
  linha = []
  for col in range(2):
    linha.append(float(input('Digite o seu salário: ')))
  salario.append(linha)
for lin in range(2):
  for col in range(2):
    soma_total = soma_total + salario[lin][col]
print()
print('A soma do salario dos funcionários é de', soma_total)

"""### 3. Faça um programa que carregue uma matriz 3 x 2, que representa preços de produtos, crie OUTRA matriz que armazene todos os preços com 7% de aumento."""

preço_produto = []
preço_aumento = []
indice = 0
for lin in range(3):
  linha = []
  for col in range(2):
    linha.append(float(input('Digite o preço do produto: ')))
  preço_produto.append(linha)
print('Matriz com preços originais: ')
print()
for lin in range(3):
  linha2 = []
  for col in range(2):
    linha2.append(preço_produto[lin][col] * 0.07 + preço_produto[lin][col])
  preço_aumento.append(linha2)
for lin in range(3):
  for col in range(2):
    indice = indice + 1
    print('O preço do produto', indice,'é', preço_aumento[lin][col])

"""### 4. Faça um programa para armazenar em uma matriz 5x2 preços. Encontre e apresente os ÍNDICES dos valores menores que 23 reais."""

matriz = []
for lin in range(5):
    linha = []
    for col in range(2):
        linha.append(int(input('Digite o valor ['+ str(lin) + '][' + str(col) + ']: ')))
    matriz.append(linha)

for lin in range(5):
    for col in range(2):
        print(matriz[lin][col], end='\t')
    print()

for lin in range(5):
    for col in range(2):
        if matriz[lin][col] < 23:
            print(f'O valor {matriz[lin][col]} na linha {lin} e na coluna {col}.')

"""### 5. Faça um programa que leia números inteiros m e n e os elementos de uma matriz A de números inteiros de dimensão m x n e conte o número de elementos que são iguais a zero.

"""

matriz = []
cont = 0
m = int(input('Informe um valor para a linha: '))
n = int(input('Informe um valor para a coluna: '))
print()

for lin in range(m):
    linha = []
    for col in range(n):
        linha.append(int(input('Digite o valor ['+ str(lin) + '][' + str(col) + ']: ')))
    matriz.append(linha)

for lin in range(m):
    for col in range(n):
        print(matriz[lin][col], end='\t')
    print()
for lin in range(m):
    for col in range(n):
        if matriz[lin][col] == 0:
            cont += 1
            print(f'O valor {matriz[lin][col]} está 0 na linha {lin} e na coluna {col}.')
print('A quantidade total de 0 é',cont)

"""### 6. Faça um programa que carregue: *um vetor com oito posições com os nomes das lojas; * um outro vetor com quatro posições com os nomes dos produtos; * uma matriz (8 x 4) com os preços de todos os produtos em cada loja. O programa deve mostrar todas as relações (nome da loja - nome do produto e preço), nas quais o preço não ultrapasse R$ 120,00.

"""

loja = []
for i in range(4):
    loja.append(input('Informe o nome da loja: '))

produto =[]
for i in range(2):
    produto.append(input('Informe o produto: '))

valor_produto = []
for lin in range(4):
    linha = []
    for col in range(2):
        linha.append(float(input('Digite o valor ['+ str(lin) + '][' + str(col) + ']: ')))
    valor_produto.append(linha)

for linha in range(4):
    for coluna in range(2):
        if valor_produto[linha][coluna] < 120:
            print(f' A loja {loja[linha]'}