# -*- coding: utf-8 -*-
"""João Pedro Artero - 221_EntradaSaida_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BkpDcWU0T20SJKCl3uGh0tqHrhJlNl0z

# Exercícios para construir programas com ENTRADA, PROCESSAMENTO e SAÍDA

### 1. Faça um programa que leia um número, multiplique ele por 2 e apresente o resultado.
      LEIA numero
      resultado = numero * 2
      ESCREVA resultado
"""

numero = int(input("Insira um número: "))
resultado = numero * 2
print(resultado)

"""### 2. Faça um programa que:
* receba três números inteiros
* calcule e mostre a soma desses números.

"""

n1 = int(input("digite um número"))
n2 = int(input("digite um número"))
n3 = int(input("digite um número"))
resultado = n1+n2+n3
print (resultado)

n1 = int(input("Insira o numero 1: "))
n2 = int(input("Insira o numero 2: "))
n3 = int(input("Insira o numero 3: "))
resultado = n1 + n2 + n3
print(resultado)

"""### 3. Faça um programa que receba três notas, calcule e mostre a média aritmética.
      LEIA nota1, nota2, nota3
      media = (nota1 + nota2 + nota3) / 3
      ESCREVA media
      
"""

nota1 = float(input("sua nota 1 "))
nota2 = float(input("sua nota 2 "))
nota3 = float(input("sua nota 3 "))
media = (nota1+nota2+nota3) / 3
print (media)

n1 = float(input("Insira a primeira nota: "))
n2 = float(input("Insira a segunda nota: "))
n3 = float(input("Insira a terceira nota: "))
resultado = (n1+n2+n3) / 3
print(resultado)

"""### 4. Faça um programa que:
* receba o salário de um funcionário
* calcule e mostre o novo salário, sabendo-se que este sofreu um aumento de 25%.

      LEIA salario
      novoSalario = salario + (salario * 25 / 100)
      ESCREVA novoSalario
"""

salario = float(input("digite seu salario"))
novosalario = salario + (salario * 25 / 100)
print (novosalario)

salario = float(input("Insirar o seu salário em R$: "))
novosalario = salario + (salario * 25 / 100)
print(novosalario)

"""### 5. Faça um programa que receba o salário de um funcionário e o percentual de aumento, calcule e mostre o valor do aumento e o novo salário.

"""

salario = float(input("digite seu salário"))
porcentagem = float(input("digite a porcentagem"))
novosalario = salario + (salario * porcentagem / 100)
print ("teu novo salário é: ",novosalario)

salario = float(input("Insira o seu salário: "))
porcentagem = float(input("Insira a porcentagem de aumento: %"))
novosalario = salario + (salario * porcentagem / 100)
print("Seu novo salário é ",novosalario)

"""### 6. Faça um programa que receba o salário base de um funcionário, calcule e mostre o salário a receber, sabendo-se que o funcionário tem gratificação de 5% sobre o salário base e **paga imposto** de 7% também sobre o salário base."""

salario = float(input("SALÁRIO: "))
gratificação = salario * 5 / 100
imposto = salario * 7 / 100
salariofinal = salario - imposto + gratificação
print ("Seu salário: ",salariofinal)

salario = float(input("Insira o valor do seu salario: R$"))
imposto = salario * 7 / 100
gratificacao = salario * 5 / 100
salariofinal = salario - imposto + gratificacao
print("O seu salário final é: ",salariofinal)

"""### 7. Faça um programa que receba o salário base de um funcionário, calcule e mostre seu salário a receber, sabendo-se que o funcionário tem gratificação de 50,00 sobre o salário base e paga imposto que deve ser lido e é aplicado sobre o salário base.

    LEIA salario, perImposto
    imposto = salario * perImposto / 100
    salario_a_receber = salario + 50 - imposto
    ESCREVA salario_a_receber
"""

salario = float (input("DEGETE SEU SALARINHO: "))
imposto = float (input("imposto a pagar"))
imposto = salario * imposto / 100
salarionovo = salario + 50 - imposto
print (salarionovo)

salariobase = float(input("Insira o valor do seu salário: R$ "))
porcentagem = float(input("Insira a porcentagem do imposto: % "))
imposto = salario * porcentagem / 100
salario_a_receber = salario + 50 - imposto
print(salario_a_receber)

"""### 8. Faça um programa que receba o valor de um depósito e o valor da taxa de juros, calcule e mostre o valor do rendimento e o valor total depois do rendimento de um mês."""

from typing import MutableSequence
deposito = float(input("digite o valor do deposito "))
juros = float(input("digite o valor da taxa de juros "))
rendimento = deposito * juros / 100
rendimentomes = rendimento * 30
print ("rendimento", rendimentomes)

deposito = float(input("Insira o valor do depósito: R$: "))
taxajuros = float(input("insira a porcentagem dos juros mensal: % "))
rendimento = deposito * taxajuros / 100
rendimentoTotal = deposito + rendimento
print("O rendimento será de ",rendimento,"%")
print("Você terá R$ {} após um mês.".format(rendimentoTotal))

"""### 9. Faça um programa que calcule e mostre a área de um triângulo. Sabe-se que: Área = (base * altura) / 2."""

base = float(input("Insira a medida da base: "))
altura = float(input("Insira a medida da altura: "))
area = (base * altura) / 2
print(area)

"""### 10. Faça um programa que calcule e mostre a área de um círculo. Sabe-se que: area = pi * raio² ou area = 3.1415 * raio²"""

raio = float(input("digite o raio² "))
pi = 3.1415
area = pi * (raio * raio)
print (area)

raio = float(input("Insira o valor do raio: "))
pi = 3.1415
area = pi * (raio ** 2)
print(area)

raio = float(input("Insira a área do raio²: "))
pi = 3.1415
area = pi * (raio ** 2)
print(area)

"""### 11. Faça um programa que receba um número, calcule e mostre:
* O número digitado ao quadrado
* O número digitado ao cubo
* A raiz do número digitado
* A raiz cúbica do número digitado

      LEIA numero
      quadrado = numero ** 2
      cubo = numero ** 3
      raiz_quadrada = numero ** (½) (meio, ou 0.5)
      raiz_cubica = numero ** (⅓) (um terço, ou 0.33)
      ESCREVA quadrado, cubo, raiz_quadrada, raiz_cubica
"""

numero = float(input("Insira um número para calculo: "))
quadrado = numero ** 2
cubo = numero ** 3
raiz_quadrada = numero ** (1/2)
raiz_cubica = numero ** (1/3)
print(quadrado)
print(cubo)
print(raiz_quadrada)
print(raiz_cubica)

numero = float(input("Insira um número para calculo: "))
quadrado = numero ** 2
cubo = numero ** 3
raiz_quadrada = numero ** (1/2)
raiz_cubica = numero ** (1/3)
print(quadrado)
print(cubo)
print(raiz_quadrada)
print(raiz_cubica)

"""### 12. Faça um programa que receba dois números, calcule e mostre um elevado ao outro. Use os caracteres **

"""

numero = float(input("Digite um numero "))
numero2 = float(input("Degete mais um numero "))
elevado = numero **numero2
print ("resultado",elevado)

numero = float(input("Insira o valor de um numero para calculo: "))
numero2 = float(input("Insira o valor do segundo numero para o calculo: "))
resultado = numero ** numero2
print(resultado)

numero1 = float(input("Insira o primeiro número: "))
numero2 = float(input("Insira o segundo número: "))
resultado = numero1 ** numero2
print(resultado)

"""### 13. Sabe-se que:

* pé = 12 polegadas
* 1 jarda = 3 pés
* 1 milha = 1760 jarda

Faça um programa que receba uma medida em pés, faça as conversões a seguir e mostre os resultados.

* Polegadas;
* Jardas;
* Milhas.

      LEIA pes
      polegadas = pes * 12
      jardas = pes / 3
      milhas = jardas / 1760
      ESCREVA polegadas, jardas, milhas
"""

pes = float(input("pes "))
polegadas = pes* 12
jardas = pes / 3
milhas = jardas / 1760
print ("resultado ",polegadas, jardas, milhas)

#A ideia do sistema é converter de pes para os outros tipos de medidas...
pes = float(input("Insira a medida em pes: "))
polegadas = pes * 12
jardas = pes / 3
milhas = jardas / 1760
print(polegadas,jardas,milhas)

"""### 14. Faça um programa que receba o ano de nascimento de uma pessoa e o ano atual, calcule e mostre:
* a idade atual da pessoa;
* quantos anos ela terá em 2050.
"""

nascimento = int(input("Insira o seu ano de nascimento: "))
idade = 2023 - nascimento
futuro = 2050 - nascimento
print("Você tem {} anos e em 2050 você terá {} anos.".format(idade,futuro))

"""#### 15. O custo ao consumidor de um carro novo é a soma do preço de fábrica com o percentual de lucro do distribuidor e dos impostos aplicados ao preço de fábrica. Faça um programa que receba o preço de fábrica de um veículo, o percentual de lucro do distribuidor e o percentual de impostos, calcule e mostre:
* o valor correspondente ao lucro do distribuidor;
* o valor correspondente aos impostos;
* o preço final do veículo.
        LEIA preco_fabrica
        LEIA percentual_lucro_distribuidor
        LEIA percentual_imposto
        lucro_distribuidor = preco_fabrica * percentual_lucro_distribuidor / 100
        valor_imposto = preco_fabrica * percentual_imposto / 100
        preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
        ESCREVA lucro_distribuidor
        ESCREVA valor_imposto
        ESCREVA preco_final

"""

precofabrica = float(input("Preço de Fábrica "))
plucrodistribuidor = float(input("Porcentagem do lucro "))
imposto = float(input("Porcentagem do imposto "))
lucrodistribuidor = precofabrica * plucrodistribuidor / 100
valorimposto = precofabrica * imposto/100
precofinal = precofabrica + lucrodistribuidor - valorimposto
print (lucrodistribuidor,"Lucro do distribuidor ")
print (valorimposto,"Valor do imposto ")
print (precofinal,"Valor final ")

fabrica = float(input("Insira o preço de fábrica: "))
lucro = int(input("Insira a porcentagem do lucro: % "))
imposto = int(input("Insira a porcentagem do imposto: % "))
resultado_imposto = fabrica * imposto / 100
print("O valor de impostos será {}. ".format(resultado_imposto))
resultado_lucro = fabrica * lucro / 100
print("O valor de lucro será de {}.".format(resultado_lucro))
precofinal = (fabrica - resultado_imposto) + resultado_lucro
print("O valor final do carro será de {}.".format(precofinal))

"""### 16. Faça um programa que receba o número de horas trabalhadas e o valor do salário mínimo, calcule e mostre o salário a receber, seguindo estas regras:
* a hora trabalhada vale a metade do salário mínimo.
* o salário bruto equivale ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
* o imposto equivale a 3% do salário bruto.
* o salário a receber equivale ao salário bruto menos o imposto.
      LEIA qtde_horas_trabalhadas
      LEIA valor_salario_minimo
      valor_hora_trabalhada = valor_salario_minimo / 2
      valor_salario_bruto = valor_hora_trabalhada * qtde_horas_trabalhadas
      imposto = valor_salario_bruto * 3 / 100
      valor_salario_liquido =  valor_salario_bruto - imposto
      ESCREVA valor_salario_liquido
"""

horas_trabalhadas = float(input('Quantidade de horas trabalhadas: '))
valor_salario_minimo = float(input('Valor salário mínimo: '))
valor_horas_trabalhadas = valor_salario_minimo / 2
valor_salario_bruto = valor_horas_trabalhadas * horas_trabalhadas
imposto = valor_salario_bruto * 3 / 100
valor_salario_liquido = valor_salario_bruto - imposto
print (valor_salario_liquido)

horas = float(input("Insira o numero de horas trabalhadas: "))
salariominimo = float(input("Insira o valor do salario minimo: "))
precohora = salariominimo / 2
salariobruto = horas * precohora
imposto = salariobruto * 3 / 100
salariofinal = salariobruto - imposto
print(salariofinal)

"""### 17. Um trabalhador recebeu seu salário e o depositou em sua conta bancária. Esse trabalhador emitiu dois cheques e agora deseja saber seu saldo atual. O banco criou uma taxa para a operação bancária de retirada que tem que pagar um imposto de 0.38% e o saldo inicial da conta está zerado.

      LEIA salario
      LEIA valor_cheque1
      LEIA valor_cheque2
      imposto_cheque1 = valor_cheque1 * 0.38 / 100
      saque1 = valor_cheque1 + imposto_cheque1
      imposto_cheque2 = cheque2 * 0.38 / 100
      saque2 = valor_cheque2 + imposto_cheque2
      saldo = salario - saque1 - saque2
      ESCREVA saldo

"""

salario = float(input("Valor do salário: "))
valor_cheque1 = float(input("valor do primeiro cheque: "))
valor_cheque2 = float(input("valor do segundo cheque: "))
imposto_cheque1 = valor_cheque1 * 0.38 / 100
saque1 = valor_cheque1 + imposto_cheque1
imposto_cheque2 = valor_cheque2 * 0.38 / 100
saque2 = valor_cheque2 + imposto_cheque2
saldo = salario - saque1 - saque2
print ("Seu saldo final: ", saldo)

salario = float(input("Insira o valor do salario depositado: R$ "))
cheque1 = float(input("Insira o valor do primeiro cheque: R$ "))
cheque2 = float(input("insira o valor do segundo cheque: R$ "))
impostocheque1 = cheque1 * 0.38 / 100
saque1 = cheque1 + impostocheque1
impostocheque2 = cheque2 * 0.38 / 100
saque2 = cheque2 + impostocheque2
saldo = salario - saque1 - saque2
print(saldo)

"""### 18. Faça um programa que receba a medida do ângulo (em graus) formado por uma escada apoiada no chão e encostada na parede e a altura da parede onde está a ponta da escada. Calcule e mostre a medida dessa escada. Observação: as funções trigonométricas implementadas nas linguagens de programação trabalham com medidas de ângulos em radianos.
      LEIA angulo
      LEIA altura
      import math # carrega a biblioteca matemática
      radiano = angulo * math.pi / 180
      escada = altura / math.sin(radiano)
      ESCREVA escada
**Observação**: Para usar seno em Python, deve-se usar esta linha de código **import math** e esta, no cálculo, **math.sin(numero)**

**import math**

escada = altura / **math.sin**(numero)
"""

angulo = float(input("Insira a medida em angulos: "))
altura = float(input("Insira a medida em altura: "))
import math #CHAMA A BIBLIOTECA DE MATEMATICA
radiano = angulo * math.pi / 180
escada = altura / math.sin(radiano)
print(escada)

"""###19. Sabe-se que o quilowatt de energia custa um quinto do salário mínimo. Faça um programa que receba o valor do salário mínimo e a quantidade de quilowatts consumida por uma residência. Calcule e mostre:


* o valor de cada quilowatt;
* o valor a ser pago por essa residência;
* o valor a ser pago com desconto de 15%.
      LEIA valor_salario
      LEIA qtde_quilowatt
      valor_quilowatt = valor_salario / 5
      valor_em_reais = valor_quilowatt * qtde_quilowatt
      valor_descontado = valor_em_reais * 15 / 100
      valor_com_desconto =  valor_em_reais − valor_descontado
      ESCREVA valor_quilowatt
      ESCREVA valor_em_reais
      ESCREVA valor_com_desconto

"""

valor_salario = float(input("Valor do salário: "))
qtde_quilowatt = float(input("Quantidade quilowatt "))
valor_quilowatt = valor_salario / 5
valor_em_reais = valor_quilowatt * qtde_quilowatt
valor_descontado = valor_em_reais * 15 / 100
valor_com_desconto = valor_em_reais - valor_descontado
print ("Valor de cada quilowatt: ",valor_quilowatt)
print ("Valor a ser pago ", valor_em_reais)
print ("Valor com desconto de 15%: ", valor_com_desconto)

"""### 20. Faça um programa que receba um número real, encontre e mostre:

* a parte inteira desse número;
* a parte fracionária desse número;
* o arredondamento desse número.

      LEIA numero
      parte_inteira = numero // 1
      parte_fracionaria = numero - parte_inteira
      numero_arredondado = arredonda (numero)
      ESCREVA parte_inteira
      ESCREVA parte_fracionaria
      ESCREVA numero_arredondado
      
**Observação**: Para arredondar um número em Python, usa-se a função **round(numero)**, onde se o número real/float estiver em igual distância entre o inteiro de cima e o inteiro de baixo, esta função arredonda para o número par mais próximo.


"""

numero = float(input("Insira o número: "))
parte_inteira = numero // 1
parte_fracionaria = numero - parte_inteira
numero_arredondado = round(numero)
print ("Parte inteira: ", parte_inteira)
print ("Parte fracionária: ", parte_fracionaria)
print ("Numero arredondado: ", numero_arredondado)

numero = float(input("Insira um número: "))
inteiro = numero // 1
print("A parte inteira deste número é {}".format(inteiro))
fracionario = numero - inteiro
print("A parte fracionária deste número é {}".format(fracionario))
arredondado = round(numero)
print("Este numero arredondado fica: {}".format(arredondado))

"""### 21. Faça um programa que receba uma hora formada por hora e minutos (um número real), calcule e mostre a hora digitada apenas em minutos. Lembre-se de que:
* para quatro e meia, deve-se digitar 4.30;
* os minutos vão de 0 a 59.
      LEIA hora
      h = pegar a parte inteira da variável hora
      minutos = hora − h
      conversao = (h * 60) + (minutos * 100)
      ESCREVA conversao

"""

hora = float(input("Hora: "))
h = hora // 1
minutos = hora - h
conversao = (h*60) + (minutos * 100)
print ("A conversão fica: ",conversao)

qtd_horas = float(input("Informe o numero de horas: "))
hora = qtd_horas // 1
minutos = qtd_horas - hora
conversao = (hora*60) + (minutos*100)
print(conversao,"minutos")

"""### 22. Faça um programa que receba o custo de um espetáculo teatral e o preço do convite desse espetáculo. Esse programa deverá calcular e mostrar a quantidade de convites que devem ser vendidos para que, pelo menos, o custo do espetáculo seja alcançado.

"""

custo = float(input("Insira o custo: "))
convite = float(input(" Insira o valor do convite: "))
quantidade = custo / convite
print ("A quantidade de convite deve ser de: ",quantidade)

custo = float(input("Insira o custo de produção: "))
ingresso = float(input("Insira o valor do ingresso: "))
minimo = custo / ingresso
print("O numero necessário de ingressos para vender é de {}.".format(minimo))