# -*- coding: utf-8 -*-
"""João Pedro Artero - 221_Est_Repeticao_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iob__Safk5RJu8GF3wmIECY67acJccsL

#ESTRUTURA DE REPETIÇÃO
##Todos estes algoritmos/programas podem ser implementados com o comando **while** ou **for**. Para estudar, implemente cada exercício com as **duas** estruturas de repetição.

###1. Faça um algoritmo  que mostre 10 vezes a frase “Bem vindo a Fatec!”. Pode implementar com o comando while ou for.
"""

contador = 0
while contador < 10:
    contador = contador + 1
    print("Bem vindo a Fatecquers")

for contador in range (10):
    print("Jaozinho")

"""###2. Faça um algoritmo que mostre o cumprimento ‘Olá ‘ para o nome de alguém (4 pessoas). Exemplo ‘Olá Mariana’. Pode implementar com o comando while ou for.

"""

for pessoas in range (4):
    nome = input("Seu nome :")
    print("Olá ",nome)

contador = 0
while contador < 4:
    nome = input("Insira seu nome: ")
    print("Olá ",nome)
    contador = contador + 1

"""###3. Faça um algoritmo que mostre os valores de 0 a 15. Pode implementar com o comando while ou for.

"""

contador = 0
while contador <= 15:
    print(contador)
    contador = contador +1

for contador in range (16):
    print(contador)

"""###4. Faça um algoritmo que mostre os valores de 3 a 20. Pode implementar com o comando while ou for.

"""

contador = 3
while contador <= 20:
    print(contador)
    contador = contador + 1

for contador in range (3,21):
    print(contador)

"""###5. Faça um algoritmo que calcule e mostre a tabuada do 5. Pode implementar com o comando while ou for.

"""

contador = 0
while contador <= 10:
    resultado = contador * 5
    print("5x",contador,"=",resultado)
    contador = contador + 1

for contador in range (11):
    resultado = contador * 5
    print("5x",contador,"=",resultado)

"""###6. Faça um algoritmo que receba a idade de 10 pessoas, calcule e exiba a quantidade de pessoas maiores de idade, sendo que a maioridade é obtida após completar 18 anos. Pode implementar com o comando while ou for.

"""

contador = 0
pessoasvelhas = 0
while contador < 5:
    idade = int(input("Sua idade: "))
    if idade >= 18:
        pessoasvelhas = pessoasvelhas + 1
    contador = contador + 1
print("existem ",pessoasvelhas," pessoas maiores de idade")

pessoasvelhas = 0
for contador in range (5):
    idade = int(input("Insira sua idade: "))
    if idade >= 18:
        pessoasvelhas = pessoasvelhas + 1
print("Existe",pessoasvelhas,"maiores de idade")

"""###7. Escreva um algoritmo que receba 23 números, calcule e exiba a quantidade de números pares e impares. Pode implementar com o comando while ou for.

"""

contador = 0
numeroimpar = 0
numeropar = 0
while contador <= 4:
    numero = int(input("insira o numero: "))
    if numero % 2 == 0:
        print(" este numero é par \n")
        numeropar = numeropar + 1
    else:
        print(" este numero é impar \n")
        numeroimpar = numeroimpar + 1
    contador = contador + 1
print("existem ",numeropar," numeros pares")
print("existem ",numeroimpar," numeros impares")

numeropar = 0
numeroimpar = 0
for contador in range (5):
    numero = int(input("Insira um número: "))
    if numero % 2 == 0:
        print("este numero é par \n")
        numeropar = numeropar + 1
    else:
        print("este numero é impar \n")
        numeroimpar = numeroimpar + 1
print("Existem ",numeropar," numeros pares, e ",numeroimpar," numeros impares")

"""###8. Faça um algoritmo que calcule e exiba o salário reajustado de dez funcionários de acordo com a seguinte regra (pode implementar com o comando while ou for):
## Salário até 300, reajuste de 50%;

##Salários maiores que 300, reajuste de 30%.



"""

contador = 1
while contador <= 10:
    salario = int(input("Insira seu salário: "))
    if salario <= 300:
        reajuste = 50 / 100 * salario
        salariofinal = salario + reajuste
    else:
        reajuste = 30 / 100 * salario
        salariofinal = salario + reajuste
    print("Seu salário reajustado é de: ",salariofinal)
    contador = contador + 1

for contador in range (10):
    salario = int(input("Insira seu salario: "))
    if salario <= 300:
        reajuste = 50 / 100 * salario
        salariofinal = salario + reajuste
    else:
        reajuste = 30 / 100 * salario
        salariofinal = salario + reajuste
    print("Seu salário final é de: ",salariofinal)

"""
###9. Faça um algoritmo que conheça 4 preços de produtos, some-os e mostre o resultado. Pode implementar com o comando while ou for.
"""

resultado = 0
contador = 1
while contador <= 4:
    produto = float(input("Insira o valor do produto: "))
    resultado = resultado + produto
    contador = contador + 1
print(resultado)

resultado = 0
for contador in range (4):
    produto = float(input("Insira o valor do produto: "))
    resultado = resultado + produto
print(resultado)

"""###10. Faça um algoritmo que calcule e informe a média de idades de 5 alunos. Pode implementar com o comando while ou for."""

resultado = 0
contador = 1
while contador <= 5:
    idade = int(input("Informe a sua idade: "))
    resultado = resultado + idade
    media = resultado / 5
    contador = contador + 1
print(media)

resultado = 0
for contador in range (5):
    idade = int(input("Informe a sua idade: "))
    resultado = resultado + idade
    media = resultado / 5
print(media)

"""###11. Faça um algoritmo que conheça 4 preços de produtos, calcule e mostre a média aritmética dos preços. Pode implementar com o comando while ou for.

"""

resultado = 0
contador = 1
while contador <= 4:
    preço = float(input("Insira o preço: "))
    resultado = resultado + preço
    media = resultado / 4
    contador = contador + 1
print(media)

resultado = 0
for contador in range (4):
    preço = float(input("Insira o preço: "))
    resultado = resultado + preço
    media = resultado / 4
print(media)

"""###12. Faça um programa que receba a idade e a altura de 20 pessoas. Calcule e exiba a média das alturas das pessoas com mais de 20 anos.



"""

resultado = 0
contador = 1
contaltura = 0
while contador <= 10:
    idade = int(input("Insira sua idade: "))
    altura = float(input("Insira sua altura: \n"))
    contador = contador + 1
    if idade >= 20:
        resultado = resultado + altura
        contaltura = contaltura + 1
    media = resultado / contaltura
print(media)

resultado = 0
contaltura = 0
for contador in range (3):
    idade = int(input("Insira sua idade: "))
    altura = float(input("Insira sua altura: "))
    if idade >= 20:
        resultado = resultado + altura
        contaltura = contaltura + 1
    media = resultado / contaltura
print(media)

"""###13. Faça um algoritmo que leia o preço de 20 TV, determine e apresente a média dos preços que possuem valor maior que R$ 1000. Pode implementar com o comando while ou for."""

resultado = 0
contador = 1
while contador <= 5:
    preço = float(input("Insira o preço: "))
    contador = contador + 1
    if preço > 1000:
        resultado = resultado + preço
        media = resultado / 5
print(media)

resultado = 0
for contador in range (5):
    preço = float(input("Insira o preço: "))
    if preço > 1000:
        resultado = resultado + preço
        media = resultado / 5
print(media)

"""###14. Faça um programa que calcule e apresente as tabuadas do 3 ao 7. Este exercício utiliza DUAS estruturas de repetição."""

for tabuada in range (3,8):
    for cont in range (1,11):
        resultado = tabuada * cont
        print(tabuada,"x",cont,"=",resultado)
    print()

"""###15. Faça um programa para o curso de ADS (6 módulos), cada sala tem 30 alunos, calcule e apresente os seguintes itens:
*  Quantidade de homens e mulheres de cada módulo;
*  Média de idades de cada módulo;
*  Quantidade de homens e mulheres do curso todo;
*  Média de idades do curso todo.

Observação: este exercício utiliza DUAS estruturas de repetição.
"""

acu_idade2 = 0
acu_genero_m2 = 0
acu_genero_f2 = 0

for modulos in range(1,3):
  acu_genero_f = 0
  acu_genero_m = 0
  acu_idade = 0
  for alunos in range(1,3):